name: Streamlit CI/CD Pipeline


on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Docker Buildx (for cross-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build the Docker image for your Streamlit app
      - name: Build Docker Image
        run: |
          docker build -t vikasy/streamlit-app:latest streamlit-cicd-demo/

      # Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push vikasy/streamlit-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      # Configure kubectl
      - name: Configure kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.31.1'  # Replace with your desired kubectl version

      # Set Kubernetes Context for do-blr Cluster
      - name: Set Kubernetes Context
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG_DO_BLR }}  # Add this secret to GitHub secrets
        run: |
          kubectl config use-context do-blr1-k8s-1-25-4-do-0-blr1-1677150099490

      # Create Kubernetes Secrets for Docker Registry
      - name: Create Kubernetes Secrets for Docker Registry
        run: |
          kubectl create secret docker-registry myregistrykey \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=${{ secrets.DOCKER_USERNAME }} \
            --docker-password=${{ secrets.DOCKER_TOKEN }} \
            --docker-email=your-email@example.com

      # Deploy using Helmfile
      - name: Deploy using Helmfile
        run: |
          helmfile -f helmfile.yaml apply
